pk-hack/CoilSnake

coilsnake/assets/modulelist.txt
coilsnake/model/eb/graphics.py
coilsnake/model/eb/palettes.py
coilsnake/model/eb/title_screen.py
coilsnake/modules/eb/TitleScreenModule.py
coilsnake/util/common/project.py

This seeks to address issue #17. It provides a way to edit the title screen data by exporting it to a set of PNG images representing animation frames and a YAML file describing characters' positions. Since the title screen is animated simply by swapping palettes, it is not necessary to have the same image in every frame - it simply needs to be the same size and to have a palette with the same number of colors. So far, the letters' sliding-in animation cannot be controlled, nor can the speed at which frames are played.
This is still a rather cumbersome approach, but it has the advantage of allowing editing through graphics editors instead of relying on JHack's editor.

Title Screen Module

---

coilsnake/assets/modulelist.txt
coilsnake/model/eb/graphics.py
coilsnake/modules/eb/DeathScreenModule.py
coilsnake/modules/eb/TitleScreenModule.py

Adds a Death Screen (Game Over) module to CoilSnake that can be used to edit the Death Screen's background image.
Currently the image is saved to the `Logos/` directory as I wasn't sure what the best location for it would be.
Addresses issue #81.

Death Screen Module

---

coilsnake/util/eb/native_comp.c

Release references to cached Rom data if the cache is updated.
Correctly propagate errors from `get_rom_bytes` to the top-level function.
Use a less expensive reference equality check to see if the Rom data is
the same instead of `PyObject_RichCompareBool`.

Release cached references and fix up error handling

---

coilsnake/ui/gui.py

Tested on Windows 10.
It seems like a longer term fix would be to use a fixed grid to align these elements, but this gets us pretty close to having them align.
Before:
After:

Adjust profile OptionMenu to align with other gui elements

---

coilsnake/model/eb/sprites.py
coilsnake/modules/eb/MiscTextModule.py
coilsnake/util/eb/graphics.py

Sort access to dictionaries when outputting to Rom in order to stabilize output in the face of dictionary implementation changes.
Generate the same CRC32 whether on Python 2 or 3.

Stabilize compilation across python versions.

---

coilsnake/model/common/ips.py
coilsnake/modules/eb/SwirlModule.py

The SwirlModule modifies the original Rom so it has more flexibility in writing out swirls. In order for the module decompile a modified Rom, we first test if this patch has been applied. If it has, we read from the
new swirls location instead of the original.

Fix SwirlModule so it can decompile modified Roms

---

coilsnake/modules/eb/SpriteGroupModule.py

SpriteGroups would be incorrectly matched with the underlying palette
because the palette matching code skipped the first color in the
palette. This resulted in SpriteGroups with palette 6 being written back
to the Rom during compilation as palette 5 because the two palettes only
differed by the first color in the palette.
The fix is to simply not skip the first color when performing the
palette matching.
mrtenda thinks it was done this way because some programs were
problematic in handling palettized png files and would disregard or
modify the first color in the palette.

Don't skip first color when matching SpriteGroup palettes

---

coilsnake/ui/gui.py

The idea here is to make the menu item reflect what mode you are in by switching the label between "Enable Debug Mode" and "Disable Debug Mode". Also, selecting "No" to the prompt doesn't enable/disable debug mode, it cancels the action and maintains the current preference.

Make Enabling/Disabling of Debug mode more explicit

---

coilsnake/ui/gui.py

This changes the Notebook at the top of the window to stay the same size
as the user resizes the window, while the Text control at the bottom of
the window fills the remaining space.
Additionally, the Entry controls in the window will fill horizontally as
the user resizes the window, but Labels and Buttons will stay a fixed
size.
Finally, logic is added to the `<<NotebookTabChanged>>` event so the
height of the notebook matches the height of the currently selected tab,
rather than always being sized to the height of the tallest tab.
Before:
After:

Improve UI resize behavior

---

setup.py
setup_exe.py

The "-std=99" flag isn't supported by Visual C++. It's technically only a warning, but I feel it's cleaner to not apply it in the first place on Windows.
I forgot to include the exhal dependency in setup_exe.py

Updates to setup_exe.py and setup.py

---

Makefile

The default python on my system was and still is python 2. Seeing as this is a fairly common issue I'd highly recommend replacing the "python" commands with "python3" ones.

Change python to python3

---

coilsnake/modules/eb/TitleScreenModule.py

This should fix issue #166. I did commit a minor sin by reading data from the ROM when writing but it was the best I could do considering that the data has to be moved and needs a specific memory placement.

Added support to the TitleScreenModule to fix the debug menu kirby sprite

---

coilsnake/modules/eb/CastModule.py

Applying any 'prefix' patch before subsequent dynamic name changes makes them not work and applying the 'paulas_mom_suffix' patch after them makes it not work either.

Fixed a problem related to the order of bytes changed by cast patches vs data.

---

coilsnake/modules/eb/DoorModule.py

It appears that the game needs the doors to be compiled in order. With MaternalBound-Redux there was a strange issue where two essentially equivalent map_doors.yml (one ordered, the other not) produced different results - the first worked and the other broke the doors. To prevent that, we now sort the items before compilation.

Sort the items in map_doors.yml before compiling.

---

coilsnake/modules/eb/SkipNamingModule.py

Tested and functional locally. Also now CoilSnake will throw an error if the strings in naming_skip.yml are too long, which it wouldn't before.

Fix skip naming hex bug, pk-hack#239

---

coilsnake/model/eb/palettes.py

Previously, when getting the palette from an image file with less than the expected number of colours, CoilSnake would raise an IndexError due to indexing outside the bounds of the palette array. Now, we will substitute in (0,0,0) instead.
Additionally, the palette class was refactored to avoid code duplication.

Fix palette bug when image file has less than the expected number of colours

---

coilsnake/model/eb/blocks.py

`array.tostring()` was deprecated in Python 3.2 and removed in Python 3.9 - we should use `tobytes()` instead.
See https://docs.python.org/3.8/library/array.html#array.array.tostring

Fix issue when patching with Py3.9 and newer

---

coilsnake/ui/gui.py

This change should make the window location restoring feature more consistent. On Windows, the window would shift a small amount on every startup, due to differences between the location being set by the `geometry` function, vs. the location read using the `winfo_rootx/winfo_rooty` functions. Using `winfo_x/winfo_y` instead seems to give correct results.
Additionally, when I tested on Linux, the window would also shift on every startup. I ended up finding out that this was due to the location being set to 0,0 and then the window being shifted down by my menubar - as a result, every time I started the program it would shift the window up to compensate for it being moved down (`ypos -= self.root.winfo_rooty()` would shift the window's Y position up by the height of my menubar). Now, we move …

Window location fix

---

coilsnake/modules/eb/DeathScreenModule.py

This change fixes a bug with the DeathScreenModule where, upon project upgrade from CoilSnake 4.0+, it would overwrite the user's death screen files with a freshly extracted set.

Death screen upgrade fix

---

coilsnake/model/common/blocks.py
coilsnake/model/eb/blocks.py
coilsnake/modules/common/PatchModule.py
coilsnake/modules/eb/EbModule.py
coilsnake/modules/smb/SmbModule.py
coilsnake/ui/common.py
coilsnake/ui/gui.py

Instead of being hardcoded throughout the codebase, these are now defined in variables and those variables are used throughout.
This also has a fix for a bug introduced with the last PR, where ROM compilation will fail due to a block's data being deleted. The solution is to avoid deleting the block's data in the `__exit__` function, and just let it be destroyed when the Block does.

Refactor ROM type strings + fix Block-related compilation failure

---

coilsnake/modules/eb/ExpandedTablesModule.py
coilsnake/modules/eb/MiscTablesModule.py
coilsnake/modules/eb/SpriteGroupModule.py
coilsnake/util/eb/pointer.py

As discussed in the discord. This lets NPC configs and sprite groups expand.
Please test and carefully review, I could easily have missed something up on integration.
Adding new NPCs/sprites crashes EbProjEditor. I'll be making another patch for that repo.

Expand NPC config table and sprite group table

---

coilsnake/modules/eb/SkipNamingModule.py

This fixes a small but long-standing glitch when skipping the name selection: you can hear the naming screen music briefly before the game starts. It could previously be mitigated by adding "setup_music2(0)" to any CoilSnake file (changing the music to silence) but many hacks haven't added this (probably an oversight).
This PR won't affect backwards compatibility, but recompiling the same code with this new version will result in a different ROM.

Fix brief naming music with naming skip enabled

---

coilsnake/ui/gui.py

Previously the script decompilation GUI page didn't save the project path, only the ROM path.  This is fairly annoying especially for testing the script decompilation while modifying the source code, so this simply adds that section in the preference file (which auto-saves just like the ROM path)

added preference for project in script decompilation

---

coilsnake/modules/eb/ExpandedTablesModule.py
coilsnake/modules/eb/SkipNamingModule.py
coilsnake/util/eb/pointer.py

Recently, we found an issue with the new NPC table relocation overwriting the user's custom CCS code. To avoid this, we will now check the actual code underlying a relocation, and skip writing the relocation if the code doesn't match.

Fix relocation overwrites

---

coilsnake/modules/eb/MapEventModule.py

Calculation of the bank is not as simple as adding C0, because 48 Mbit ROMs exist! And they put file addresses 40XXXX at 40XXXX in the address space, apparently. (Definitely not 101XXXX. That's not a valid SNES address.) Defer to CoilSnake's existing address translation logic instead of the + 0xC0.
Messianic reported running into this issue. Until he gets a chance to test the fix for the compilation phase, I'm marking this as a draft.

MapEventModule: fix bank calculation

---

coilsnake/util/eb/pointer.py

The RE used was not matching any pointer which contained a newline byte (0x0A). Use DOTALL to match any character.

Fix bug with regular expression (inadvertently caused pointers to not be relocated)

---

.github/workflows/pyinstaller.yaml
.gitignore
coilsnake/ui/git_commit.py
coilsnake/ui/information.py
rename_exe_with_version.py
requirements.txt
set_git_commit.py
setup.py

This PR adds GitHub action support. This will build a Windows executable whenever:
- changes are pushed into the `master` branch
- a pull request is created
This will hopefully make it easy to share development versions of CoilSnake.

Add GitHub actions, compiling CoilSnake for Windows on pushes and PRs

---

coilsnake/model/eb/musicpack.py

Recently, we've become aware of a bug. When transitioning from a song with a non-zero echo delay value to a new song which uses instrument samples that would overlap with the previous echo buffer, the samples may become corrupted independent of the echo value used by the new song. This is because the echo feature was not disabled when the instruments for the new song were uploaded.
This branch adds a new feature where CoilSnake will patch the music engine to disable echo when uploading data.
This is the assembly code added to the SPC, assembled by hand:
```
<          > ; push old echo value
< eb 4d    >     mov y, $4d
< f0 13    >     beq _exit
< 6d       >     push y
<          > ; call existing code at $0b2c with A=0 to disable echo
< e8 00    >     mov a, #0
< 3f 2c 0b >     call …
```

Patch music engine to avoid echo buffer overwriting sample data

---

.github/workflows/pyinstaller.yaml

This is required for now because of how setuptools_scm relies on tags and the number of commits since that tag (via `git describe`, I guess) to determine the version number string. (Without that info, the version will be named "0.1.dev1+g(hash)" every time, possibly even for actual releases.)
A more efficient solution may be possible in the future; see actions/checkout#249 and pypa/setuptools-scm#480
I've pushed the official `v4.2` tag to my forked repo to make sure that this works before merging it.

CI: Fetch all commits and tags

---

pyproject.toml

Fixes #312 
This change to the pyproject file updates the path to CCScriptWriter to use the Github refs pattern, which supports specifying the file extension. This works around issues with installing dependencies where the filetype could not be inferred from the `master` bundle path that did not include a filetype extension, which depended on the HTTP client to infer the filetype based on MIME type and append an extension.

Update CCScriptWriter dependency URL in pyproject

---

coilsnake/model/common/ips.py

When a ROM has a change that begins at address 454F46 (ASCII `EOF`), it can't normally be encoded in an IPS file, because that offset value is used to mark the end of the patch. CoilSnake did have code to catch that case, but it seems like it was never tested, at least not in any recent version of Python... it caused a single `int` to be inserted as the change to make to an offset, rather than a `bytes` object. All of the other code was based on `bytes` objects being appended together, so the next loop iteration would raise a TypeError (`unsupported operand type(s) for +=: 'int' and 'bytes'`)
Changes were tested by changing an all-zeroes file to have the bytes `DE AD` at offset 454F46 and confirming that the IPS patch contained a 3-byte change beginning at offset 454F45 consisting of `00 …

Fix creation of IPS patches with records beginning at 454F46

---

coilsnake/modules/eb/CompressedGraphicsModule.py

FREE_RANGES are inclusive address ranges, and E1F203 is the address of the spritemap data for the hamburger shop map marker. In rare circumstances, this could cause the very first byte (Y position) of the first portion of the sprite to be overwritten with arbitrary data, if that block of free space was filled all the way to the end.
Probably fixes #316. Hopefully @ichee can confirm that the fix works on their end?

CompressedGraphicsModule: fix bad FREE_RANGES end address
